services:
  auth:
    container_name: cromalink-api-auth
    hostname: cromalink-api-auth
    image: cromalink-api-auth
    networks:
      cromalink:
        ipv4_address: 172.18.0.11
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html

networks:
  cromalink:
    external: true
    ipam:
      config:
        - subnet: 172.18.0.0/16
          ip_range: 172.18.0.0/20
