services:
  auth:
    container_name: cromalink-api-auth
    hostname: cromalink-api-auth
    image: cromalink-api-auth
    networks:
      cromalink:
        ipv4_address: 172.18.0.11
    build:
      context: .
    env_file:
      - .env
    environment:
      - APP_NAME='Cromalink API'
      - DB_HOST=cromalink_db
      - DB_DATABASE=cromalink_db
      - DB_USERNAME=cromalink_user
      - DB_PASSWORD=Cr0m4l1nK.
      - DB_PORT=3306
      - APP_DEBUG=false

networks:
  cromalink:
    external: true
    ipam:
      config:
        - subnet: 172.18.0.0/16
          ip_range: 172.18.0.0/20
